// report-render.mjs — the exportable artifact.
//
// The deliverable is not "advice". It is a dated, hash-stamped, reproducible
// document that goes in an audit file and can be handed to counsel.
//
// The hash is the point. Re-run the engine with the same answers in 2028 and the
// stamp matches — which is exactly what an auditor asks for and exactly what no
// language model can provide.

import { createHash } from 'node:crypto';
import { assess, ENGINE_ID, ENGINE_ENCODED_ON, ENFORCEMENT_DATE, LEGAL_BOUNDARY } from './article12-engine.mjs';

export const REPORT_SCHEMA_ID = 'aiact.article12.report.v1';

/**
 * Stamp is computed over ENGINE + INPUTS + FINDINGS only.
 * Deliberately excludes the generation timestamp, so the same assessment
 * re-run later yields the SAME stamp. That is the reproducibility claim.
 */
export function stampOf(result) {
  return createHash('sha256').update(JSON.stringify({
    engine: result.engine,
    engineEncodedOn: result.engineEncodedOn,
    inputs: result.inputs,
    findings: result.findings.map(f => [f.id, f.severity, f.article]),
  })).digest('hex');
}

export function buildReport(answers, { organisation = null, systemName = null, generatedAt = null } = {}) {
  const result = assess(answers);
  const stamp = stampOf(result);
  return {
    schema: REPORT_SCHEMA_ID,
    stamp,
    organisation, systemName,
    generatedAt,                 // metadata only — NOT part of the stamp
    enforcementDate: ENFORCEMENT_DATE,
    ...result,
  };
}

const SEV = {
  BLOCKER:  { mark: '[BLOCKER] ', note: 'must be resolved — blocks lawful placement or use' },
  GAP:      { mark: '[GAP]     ', note: 'obligation applies and evidence is missing' },
  ADVISORY: { mark: '[ADVISORY]', note: 'prudent, not established as mandatory here' },
  INFO:     { mark: '[INFO]    ', note: 'context' },
  PASS:     { mark: '[PASS]    ', note: 'reported as satisfied — retain the evidence' },
};

export function toMarkdown(report) {
  const L = [];
  L.push(`# EU AI Act — Article 12 Self-Assessment`);
  L.push('');
  L.push(`**Organisation:** ${report.organisation ?? '—'}`);
  L.push(`**System:** ${report.systemName ?? '—'}`);
  L.push(`**Role:** ${report.inputs.role}`);
  L.push(`**Annex III category:** ${report.inputs.annexIII}`);
  L.push(`**High-risk obligations apply from:** ${report.enforcementDate}`);
  L.push('');
  L.push(`**Reproducibility stamp:** \`${report.stamp}\``);
  L.push(`**Engine:** ${report.engine} (rules encoded ${report.engineEncodedOn})`);
  L.push('');
  L.push('> Re-running this engine with the same answers reproduces this stamp exactly.');
  L.push('> A differing stamp means the answers or the rule set changed.');
  L.push('');
  L.push('---');
  L.push('');
  L.push('## What this document is and is not');
  L.push('');
  L.push(`This document **is** ${LEGAL_BOUNDARY.is}.`);
  L.push('');
  L.push('It is **not**:');
  for (const n of LEGAL_BOUNDARY.is_not) L.push(`- ${n}`);
  L.push('');
  L.push(`**Required next step:** ${LEGAL_BOUNDARY.required_next_step}`);
  L.push('');
  L.push(`No overall compliance verdict is issued. ${report.verdictWithheld}`);
  L.push('');
  L.push('---');
  L.push('');
  L.push('## Summary');
  L.push('');
  L.push(`| Severity | Count |`);
  L.push(`|---|---|`);
  for (const [k, v] of Object.entries(report.counts)) L.push(`| ${k} | ${v} |`);
  L.push('');

  if (report.lowConfidenceRules.length) {
    L.push('> **Encoded at low confidence — verify against the primary text before relying on these:** '
      + report.lowConfidenceRules.join(', '));
    L.push('');
  }

  L.push('---');
  L.push('');
  L.push('## Findings');
  L.push('');
  for (const f of report.findings) {
    const s = SEV[f.severity] ?? { mark: `[${f.severity}]`, note: '' };
    L.push(`### ${s.mark} ${f.title}`);
    L.push('');
    L.push(`**Article:** ${f.article}  |  **Rule:** \`${f.id}\`  |  **Encoding confidence:** ${f.confidence}`);
    L.push('');
    L.push(f.detail);
    L.push('');
    L.push(`**Action:** ${f.action}`);
    L.push('');
    L.push(`**Verify against primary text:** ${f.verify}`);
    L.push('');
  }
  L.push('---');
  L.push('');
  L.push('## Evidence checklist');
  L.push('');
  L.push('Retain the following in your technical documentation:');
  L.push('');
  for (const f of report.findings.filter(x => x.severity !== 'INFO')) {
    L.push(`- [ ] **${f.article}** — ${f.title}`);
  }
  L.push('');
  L.push('---');
  L.push('');
  L.push('*Generated by a deterministic rule engine. No language model was used, no data left the machine on which it ran, and no network call was made.*');
  return L.join('\n');
}

export function toJSON(report) { return JSON.stringify(report, null, 2); }

/** Minimal self-contained HTML. No CDN, no fonts, no tracking — it must open offline in 2028. */
export function toHTML(report) {
  const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
  const rows = report.findings.map(f => `
    <div class="f ${esc(f.severity.toLowerCase())}">
      <h3><span class="sev">${esc(f.severity)}</span> ${esc(f.title)}</h3>
      <p class="meta">${esc(f.article)} &middot; <code>${esc(f.id)}</code> &middot; confidence: ${esc(f.confidence)}</p>
      <p>${esc(f.detail)}</p>
      <p><strong>Action:</strong> ${esc(f.action)}</p>
      <p class="verify"><strong>Verify:</strong> ${esc(f.verify)}</p>
    </div>`).join('');
  return `<!doctype html><meta charset="utf-8"><title>Article 12 Self-Assessment</title>
<style>
 body{font:15px/1.6 system-ui,sans-serif;max-width:820px;margin:2rem auto;padding:0 1rem;color:#161616}
 .stamp{font-family:ui-monospace,monospace;font-size:12px;word-break:break-all;background:#f4f4f4;padding:.6rem;border-radius:4px}
 .boundary{border-left:4px solid #d97706;background:#fffbeb;padding:.8rem 1rem;margin:1.5rem 0}
 .f{border-left:4px solid #ccc;padding:.4rem 1rem;margin:1.4rem 0}
 .f.blocker{border-color:#dc2626}.f.gap{border-color:#ea580c}
 .f.advisory{border-color:#ca8a04}.f.pass{border-color:#16a34a}.f.info{border-color:#94a3b8}
 .sev{font-family:ui-monospace,monospace;font-size:11px;padding:.15rem .45rem;background:#eee;border-radius:3px;vertical-align:middle}
 .meta{color:#666;font-size:13px}.verify{color:#666;font-size:13px}
</style>
<h1>EU AI Act — Article 12 Self-Assessment</h1>
<p><strong>Organisation:</strong> ${esc(report.organisation ?? '—')}<br>
<strong>System:</strong> ${esc(report.systemName ?? '—')}<br>
<strong>Role:</strong> ${esc(report.inputs.role)}<br>
<strong>Obligations apply from:</strong> ${esc(report.enforcementDate)}</p>
<p class="stamp">Reproducibility stamp<br>${esc(report.stamp)}</p>
<div class="boundary">
<p><strong>This is ${esc(LEGAL_BOUNDARY.is)}.</strong></p>
<p>It is <em>not</em> ${LEGAL_BOUNDARY.is_not.map(esc).join(', not ')}.</p>
<p>${esc(LEGAL_BOUNDARY.required_next_step)}.</p>
</div>
<h2>Findings</h2>${rows}
<hr><p style="color:#666;font-size:13px">Generated by a deterministic rule engine. No language model was used, no data left this machine, no network call was made.</p>`;
}
