#!/usr/bin/env bun
// Orange5 DX — ledger-sync
//
// Reads the FULL verifier's `--json` ground truth and regenerates the
// "CLOSED THIS PASS" status block for the Not-Green Ledger — from real counts,
// never from prose. What "closed this pass" means, honestly: the set of test
// files the verifier now reports GREEN, and the set still RED (which cannot be
// claimed closed). The generated block reports:
//   * headline count  (green/total, pct, all-green?)
//   * the RED files that remain OPEN (verbatim from verifier: file, code, tail)
//   * a machine-generated timestamp
//
// SAFETY (anti-drift): this tool does NOT blindly overwrite the operator's
// hand-authored ledger. Two modes:
//   * default        -> write a sibling artifact ORANGE5_NOT_GREEN_LEDGER.synced.md
//   * --splice       -> splice the generated block into the real ledger ONLY
//                       between explicit markers:
//                         <!-- LEDGER-SYNC:START --> ... <!-- LEDGER-SYNC:END -->
//                       If the markers are absent, it refuses to edit and falls
//                       back to the sibling artifact (never a silent rewrite).
//
// The verifier is spawned READ-ONLY; its exit 1 (reds present) is expected.
//
// Usage:
//   bun 00-CHARTER/tools/ledger-sync.mjs                 # write .synced.md sibling
//   bun 00-CHARTER/tools/ledger-sync.mjs --dry-run       # print block to stdout
//   bun 00-CHARTER/tools/ledger-sync.mjs --splice        # into real ledger IF markers
//   bun 00-CHARTER/tools/ledger-sync.mjs --json          # machine summary
//
// Programmatic:  import { renderClosedBlock, spliceBetweenMarkers } from './ledger-sync.mjs'
//
// Mom's Law: reds cannot be marked closed. The block is verifier ground truth.

import { readFileSync, writeFileSync, existsSync } from 'node:fs';
import { dirname, join, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { runBadge, badgeFromVerifierJson } from './verifier-badge.mjs';

export const ROOT = resolve(dirname(fileURLToPath(import.meta.url)), '..', '..');
export const LEDGER_PATH = join(ROOT, '00-CHARTER', 'ORANGE5_NOT_GREEN_LEDGER.md');
export const SYNCED_PATH = join(ROOT, '00-CHARTER', 'ORANGE5_NOT_GREEN_LEDGER.synced.md');
export const MARK_START = '<!-- LEDGER-SYNC:START -->';
export const MARK_END = '<!-- LEDGER-SYNC:END -->';

// Pure renderer: verifier JSON (or badge+reds) -> markdown status block.
// Exported so it can be unit-tested against a fixed payload with no spawn.
export function renderClosedBlock(verifierJson, now = new Date()) {
  const badge = badgeFromVerifierJson(verifierJson, now);
  const reds = Array.isArray(verifierJson.reds) ? verifierJson.reds : [];
  const stamp = now.toISOString();

  const lines = [];
  lines.push(MARK_START);
  lines.push('');
  lines.push('## CLOSED THIS PASS — verifier ground truth (auto-generated)');
  lines.push('');
  lines.push(`_Generated by \`00-CHARTER/tools/ledger-sync.mjs\` from \`bun run verify:json\` at ${stamp}. Do not hand-edit between the markers._`);
  lines.push('');
  lines.push(`**Headline:** ${badge.green} / ${badge.total} test files GREEN (${badge.pct}%).` +
    (badge.allGreen ? ' Full surface green — no open reds.' : ` **${badge.red} RED remain OPEN** (cannot be marked closed).`));
  lines.push('');

  if (badge.allGreen) {
    lines.push('Every discovered test file passed its correct invocation. No red may hide: the count is over the whole surface, not a hand-picked subset.');
  } else {
    lines.push('### STILL RED — not closed');
    lines.push('');
    lines.push('| # | Test file | Exit | Timed out | Tail |');
    lines.push('|---|---|---|---|---|');
    reds.forEach((r, i) => {
      const file = String(r.file ?? '?').replace(/\|/g, '\\|');
      const tail = String(r.tail ?? '').replace(/\|/g, '\\|').slice(0, 80);
      lines.push(`| ${i + 1} | \`${file}\` | ${r.code ?? '?'} | ${r.timedOut ? 'yes' : 'no'} | ${tail} |`);
    });
  }
  lines.push('');
  lines.push(MARK_END);
  return lines.join('\n');
}

// Splice the generated block between the two markers in an existing document.
// Returns { spliced: boolean, content: string }. Never partial-writes.
export function spliceBetweenMarkers(doc, block) {
  const s = doc.indexOf(MARK_START);
  const e = doc.indexOf(MARK_END);
  if (s === -1 || e === -1 || e < s) return { spliced: false, content: doc };
  const before = doc.slice(0, s);
  const after = doc.slice(e + MARK_END.length);
  // `block` already includes both markers.
  return { spliced: true, content: before + block + after };
}

// ---- CLI ----
function parseArgs(argv) {
  return {
    dryRun: argv.includes('--dry-run'),
    splice: argv.includes('--splice'),
    json: argv.includes('--json'),
  };
}

function main() {
  const o = parseArgs(process.argv.slice(2));
  const { raw } = runBadge();            // read-only verifier spawn; tolerates exit 1
  const now = new Date();
  const block = renderClosedBlock(raw, now);
  const badge = badgeFromVerifierJson(raw, now);

  if (o.dryRun) {
    if (o.json) console.log(JSON.stringify({ badge, wrote: false, target: 'dry-run' }, null, 2));
    else console.log(block);
    return;
  }

  if (o.splice) {
    if (!existsSync(LEDGER_PATH)) {
      console.error(`[ledger-sync] ledger not found at ${LEDGER_PATH}; writing sibling instead.`);
    } else {
      const doc = readFileSync(LEDGER_PATH, 'utf8');
      const { spliced, content } = spliceBetweenMarkers(doc, block);
      if (spliced) {
        writeFileSync(LEDGER_PATH, content);
        const msg = `[ledger-sync] spliced auto-block into ${LEDGER_PATH} (${badge.green}/${badge.total} green)`;
        if (o.json) console.log(JSON.stringify({ badge, wrote: true, target: LEDGER_PATH, mode: 'splice' }, null, 2));
        else console.log(msg);
        return;
      }
      console.error(`[ledger-sync] markers ${MARK_START} / ${MARK_END} not found in ledger; NOT editing it. Writing sibling instead.`);
    }
  }

  // default / fallback: sibling artifact, never touches the operator's file.
  const doc = `# Orange5 — Not-Green Ledger (verifier-synced view)\n\n` +
    `_Auto-generated companion to \`ORANGE5_NOT_GREEN_LEDGER.md\`. Ground truth only._\n\n${block}\n`;
  writeFileSync(SYNCED_PATH, doc);
  if (o.json) console.log(JSON.stringify({ badge, wrote: true, target: SYNCED_PATH, mode: 'sibling' }, null, 2));
  else console.log(`[ledger-sync] wrote ${SYNCED_PATH}  (${badge.green}/${badge.total} green, ${badge.red} red)`);
}

if (import.meta.main) main();
